### ISSUE TITLE
Throws Agent JAR loaded but agent failed to initialize

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patric-r/jvmtop#20]
```
What steps will reproduce the problem?
1.Process running under root.
2.Execute jvmtop.sh <pid> at command-line


What is the expected output? What do you see instead?
Throws below exception:
[ java.io.IOException: Agent JAR loaded but agent failed to initialize
	at com.jvmtop.openjdk.tools.LocalVirtualMachine.loadManagementAgent(LocalVirtualMachine.java:378)
	at com.jvmtop.openjdk.tools.LocalVirtualMachine.startManagementAgent(LocalVirtualMachine.java:137)
	at com.jvmtop.openjdk.tools.ProxyClient.tryConnect(ProxyClient.java:367)
	at com.jvmtop.openjdk.tools.ProxyClient.connect(ProxyClient.java:349)
	at com.jvmtop.VMInfo.attachToVM(VMInfo.java:207)
	at com.jvmtop.VMInfo.processNewVM(VMInfo.java:163)
	at com.jvmtop.VMDetailView.<init>(VMDetailView.java:26)
	at com.jvmtop.JvmTop.main(JvmTop.java:35)
Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded 
but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:103)
	at com.jvmtop.openjdk.tools.LocalVirtualMachine.loadManagementAgent(LocalVirtualMachine.java:368)
	... 7 more ]

What version of jvmtop are you using? On what operating system?
jvmtop version : jvmtop 0.6.0 alpha

Please post the output of the following commands:
java -version :
java version "1.6.0_16"
Java(TM) SE Runtime Environment (build 1.6.0_16-b01)
Java HotSpot(TM) 64-Bit Server VM (build 14.2-b01, mixed mode) 

echo $JAVA_HOME  (for unix/linux systems):
/opt/jdk1.6.0_16

echo %JAVA_HOME% (for windows)


Please provide any additional information below.


```

Original issue reported on code.google.com by `yamini.p...@gmail.com` on 17 Jun 2013 at 4:30

**Comment by patric-r** [comment]
Closing, assuming that the bug is fixed.
If you still can reproduce the issue please open a new one.
