### ISSUE TITLE
Improve error message for AttachNotSupportedException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Patric-R/jvmtop#59]
```
Before submitting a bug report, please check the FAQ:
http://code.google.com/p/jvmtop/wiki/FAQ

In Issue 2, Patric wrote:
>>If you're still having some problems with ibm jdk - just reopen a new issue
ok, here's that new issue.

What steps will reproduce the problem?
1. Using IBM R27_Java727_SR2_20141215_1631_B227395

2. JvmTop using same JVM as the pid to be traced.
The attached file shows the JVM path for jvmtop and my pid are the exact same 
path.

3. Using JDK instead of JRE.
The attached .txt file shows I'm using a JDK, not a JRE.

4. JvmTop is running under same user as pid to be traced.
Attached .txt file includes output of "ps -ef" for my pid, which shows user is 
ngapp2.
Output also shows "whoami" before running jvmtop -- also ngapp2

What is the expected output? What do you see instead?

I was hoping the error message would tell me what I needed to change to fix the 
problem.
For example, 
* the error message could compare the path of the jvmtop to the path of the 
pid's JVM.
* the error message could compare the user of jvmtop to the user of the pid.
* the error message could indicate the specific path where it was expecting to 
find tools.jar,
or other info that indicated why it thought a JRE was in use instead of a JVM.

What version of jvmtop are you using? On what operating system?
jvmtop 0.8.0
Red Hat Enterprise Linux Server release 6.6 (Santiago)



Please post the output of the following commands:
java -version
echo $JAVA_HOME  (for unix/linux systems)
echo %JAVA_HOME% (for windows)

See attached AttachNotSupportedException.txt for details.

Please provide any additional information below.

Here is the error I'm getting:

com.ibm.tools.attach.AttachNotSupportedException: target not found
        at com.ibm.tools.attach.javaSE.VirtualMachineImpl.attachTarget(VirtualMachineImpl.java:87)
        at com.ibm.tools.attach.javaSE.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:37)
        at ibm.tools.attach.J9AttachProvider.attachVirtualMachine(J9AttachProvider.java:56)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:237)
        at com.jvmtop.openjdk.tools.LocalVirtualMachine.getLocalVirtualMachine(Unknown Source)
        at com.jvmtop.view.VMDetailView.<init>(Unknown Source)
        at com.jvmtop.JvmTop.main(Unknown Source)
Exception in thread "main" com.sun.tools.attach.AttachNotSupportedException: 
target not found
        at ibm.tools.attach.J9AttachProvider.attachVirtualMachine(J9AttachProvider.java:61)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:237)
        at com.jvmtop.openjdk.tools.LocalVirtualMachine.getLocalVirtualMachine(Unknown Source)
        at com.jvmtop.view.VMDetailView.<init>(Unknown Source)
        at com.jvmtop.JvmTop.main(Unknown Source)

```

Original issue reported on code.google.com by `eostermu...@gmail.com` on 5 Mar 2015 at 5:52

Attachments:
- [AttachNotSupportedException.txt](https://storage.googleapis.com/google-code-attachments/jvmtop/issue-59/comment-0/AttachNotSupportedException.txt)

**Comment by patric-r** [comment]
Hi,
thanks for the detailed bug report.

In order to have a chance to reproduce this:
Which exact Websphere 8.5 release are you using (Fixpack number?)?
Are the JRE settings on their factory defaults or have you made some changes?

Thanks.
