### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Patric-R/jvmtop#62]
```
I ran jvmtop.sh on an ec2 instance which is hosting a tomcat web application. 
When I ran the sh, i do not get jvm metrics related to the web application. I 
only get the metrics related to m.jvmtop.JVMTOP. 

When i try to run the jvmtop.sh with a pid for tomcat, i get the following 
exception.

What steps will reproduce the problem?
1. jvmtop.sh <pid>
2.
3.

What is the expected output? What do you see instead?
Exception in thread "main" java.io.IOException: Operation not permitted
    at sun.tools.attach.LinuxVirtualMachine.sendQuitTo(Native Method)
    at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:91)
    at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
    at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:213)
    at com.jvmtop.openjdk.tools.LocalVirtualMachine.getLocalVirtualMachine(Unknown Source)
    at com.jvmtop.view.VMDetailView.<init>(Unknown Source)
    at com.jvmtop.JvmTop.main(Unknown Source)

What version of jvmtop are you using? On what operating system?

0.8.0 jvmtop

Linux Ubuntu


Please post the output of the following commands:
java -version  Oracle 7
echo $JAVA_HOME  (for unix/linux systems)  /usr/lib/jvm/java-7-oracle



Please provide any additional information below.


```

Original issue reported on code.google.com by `medha.sr...@gmail.com` on 3 May 2015 at 8:45

**Comment by patric-r** [comment]
Are you running jvmtop as the same user as the tomcat instance?

**Comment by markyzb** [comment]
Any update on this problem, we see this exception in our application.

**Comment by patric-r** [comment]
@markyzb would you please answer my question: Are you running jvmtop as the same user as the tomcat instance?

**Comment by markyzb** [comment]
No, I am not running tomcat. 
However, I have find the problem due to the incorrect permission of the folder /tmp/hsperfdata_XXXX
