### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/jvmtop/JvmTop

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patric-r/jvmtop#63]
```
Before submitting a bug report, please check the FAQ:
http://code.google.com/p/jvmtop/wiki/FAQ

uname -a
===========
Linux 2.6.32-279.11.1.el6.x86_64 #1 SMP EDT 2012 x86_64 x86_64 x86_64 GNU/Linux
===========

jvmtop-a3904b5b7e3a

./jvmtop.sh
============
Exception in thread "main" java.lang.NoClassDefFoundError: com/jvmtop/JvmTop
Caused by: java.lang.ClassNotFoundException: com.jvmtop.JvmTop
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: com.jvmtop.JvmTop. Program will exit.
============

output of the following commands:

java -version
=======
java version "1.6.0_34"
OpenJDK Runtime Environment (IcedTea6 1.13.6) (rhel-1.13.6.1.el6_6-x86_64)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
=======

echo $JAVA_HOME  (for unix/linux systems)
======
/usr/lib/jvm/java-1.6.0-openjdk.x86_64/
======



```

Original issue reported on code.google.com by `pushpa.s...@gmail.com` on 22 May 2015 at 6:22

**Comment by patric-r** [comment]
Have you extracted all of the files in the downloaded tar.gz? Can you check whether jvmtop.jar is present?

**Comment by patric-r** [comment]
Closed due to lacking answers. Feel free to reopen if this issue happens again.
